# Generated by Django 4.1.7 on 2023-03-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/events/')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('about', models.TextField(max_length=2000)),
                ('popularity', models.PositiveSmallIntegerField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Events.hall')),
            ],
        ),
    ]
