# Generated by Django 4.1.7 on 2023-03-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/news/')),
                ('about', models.TextField(max_length=2000)),
                ('link', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
